version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - 🧩 dependencies
      - 🤖 bot
    groups:
      all-docker-updates:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - 🧩 dependencies
      - 🤖 bot
    groups:
      all-github-actions-updates:
        patterns:
          - "*"
